name: Build latest
on:
  push:
    branches:
      - '**'
      - '!master'

  pull_request:
    branches:
      - master

jobs:
  # Temporarily keeping this for comparison
  latex-local:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Dockerfile
        run: |
          docker build -t docker_img:latest -f ./.devcontainer/Dockerfile .
          docker run -v $GITHUB_WORKSPACE:/workspace -w /workspace docker_img:latest make

  latex-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build latex
        uses: aalbaali/latex-action@master
        with:
          root_file: |
            src/main.tex
          work_in_root_file_dir: true

          # Args:
          #   -cd                 :   Change directory to the root file (this way it can find the cc.tex file)
          #   -pdf                :   Generate a PDF using pdflatex
          #   --output-directory  :   Build directory, with respect to the calling command
          # For more info, refer to
          #   https://manpages.ubuntu.com/manpages/bionic/man1/latexmk.1L.html
          args: -cd -pdf --output-directory=../build

      - name: Upload PDF
        uses: actions/upload-artifact@v2
        with:
          name: output_pdf
          path: build/main.pdf


  update-wiki:
    runs-on: ubuntu-latest
    needs: latex-action
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Checkout wiki
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}.wiki
          path: wiki
          fetch-depth: 0
            
      - name: Download pdf
        uses: actions/download-artifact@v2
        with:
          name: output_pdf

      - name: Get current date
        id: date
        run: echo "date=$(TZ=America/New_York date +'%d-%b-%Y %H:%m')" >> $GITHUB_OUTPUT

      - name: Move and rename pdf
        run: |
          mkdir -p wiki/data
          mv main.pdf wiki/data/${{ github.event.repository.name }}.pdf      

      - name: Add pdf to wiki
        run: |
          echo Latest build info >> wiki/Home.md
          echo \`\`\` > wiki/Home.md
          echo Author: ${{ github.actor }} >> wiki/Home.md
          echo Branch: ${{ github.head_ref }} >> wiki/Home.md
          echo Commit: ${{ github.sha }} >> wiki/Home.md
          echo \`\`\` >> wiki/Home.md
          echo 'Latest [PDF](data/${{ github.event.repository.name }}.pdf) built on ${{ steps.date.outputs.date }}' >> wiki/Home.md
          cd wiki
          git config user.name homework-bot
          git config user.email homework-bot@github.com
          git add .
          git commit -m "Update pdf: ${{ github.sha }}" --allow-empty
          git push
